name: Build

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - packages/**

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - run: npx turbo run build --filter=@wethegit/react-hooks
